package com.ghostlock.app.data.component

import com.ghostlock.app.data.StepSetKind
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Guards for [StepSequenceCatalog]: the stepset -> step sequence comes from the
 * native-exported manifest, covers EVERY StepSetKind, and never falls back to a
 * hand-written or empty list.
 */
class StepSequenceCatalogTest {

    @Test
    fun `the three stepsets expand to their execution order`() {
        assertEquals(listOf("w1", "w2"), StepSetKind.W1W2.stepNames())
        assertEquals(listOf("w1", "w2", "w3"), StepSetKind.W1W3.stepNames())
        assertEquals(listOf("pagecache_write"), StepSetKind.PAGE_CACHE_WRITE.stepNames())
    }

    @Test
    fun `every StepSetKind is covered by the manifest`() {
        for (kind in StepSetKind.entries) {
            assertTrue(
                "the manifest must declare " + kind.token,
                StepSequenceCatalog.declaredStepsets.contains(kind.token),
            )
            assertTrue(
                "every stepset needs at least one step: " + kind.token,
                kind.stepNames().isNotEmpty(),
            )
        }
        /* And the manifest may not invent a stepset the enum does not know. */
        val known = StepSetKind.entries.map { it.token }.toSet()
        for (token in StepSequenceCatalog.declaredStepsets) {
            assertTrue("unknown stepset in the manifest: " + token, token in known)
        }
    }

    @Test
    fun `the manifest resource is the native-exported one`() {
        /* The runtime copy is regenerated by `make -C src stepset-steps-manifest`
         * and pinned by the native host test of the same name; this asserts the
         * pairing exists so a renamed/removed exporter cannot go unnoticed. */
        val repo = generateSequence(File(System.getProperty("user.dir")).canonicalFile) {
            it.parentFile
        }.first { File(it, "src/core/tests/stepset_steps_manifest_test.cpp").isFile }
        val appCopy = File(repo, "app/src/test/resources/" + StepSequenceCatalog.RESOURCE)
        val runtimeCopy = File(
            repo,
            "profile-core/src/main/resources/" + StepSequenceCatalog.RESOURCE,
        )
        assertTrue("the app-side copy must exist", appCopy.isFile)
        assertTrue("the runtime copy must exist", runtimeCopy.isFile)
        assertEquals(
            "the two committed copies must stay byte-identical",
            appCopy.readText(),
            runtimeCopy.readText(),
        )
    }
}
