package com.ghostlock.app.data.profile

import com.ghostlock.app.data.NativeProfileDocument
import com.ghostlock.app.data.QueueElement
import com.ghostlock.app.data.component.BackendKind
import com.ghostlock.app.data.component.CombinationCatalog
import com.ghostlock.app.data.plugin.PluginValue
import com.ghostlock.app.data.route.RouteKind

/**
 * NativeProfileDocument (logical model) -> Glkv3Document path/type adapter
 * (GLKv3-3, S4 R2).
 *
 * This adapter is the production logical-document translation
 * used by `exportProfiles` and the app native-document path (GLKv3-4).
 * It consumes [NativeProfileDocument.v3Sections], the owner-qualified and
 * selection-aware emission (only the selection's owners plus `common`).
 *
 * S4 R2 removes the hand-written path -> type table: the map is generated from
 * the native-exported GLKv3 manifest `profile-manifest-v3.tsv` (owner, path, wire,
 * required, default, source, doc) shipped as a profile-core runtime resource.
 * A key or wire type that drifts on either side fails
 * ProfileManifestV3AgreementTest instead of silently reaching production.
 *
 * The root selection keys are tokens (release / terminal / backend / route), as
 * the GLKv3 root map declares.
 */
object NativeProfileGlkv3Adapter {
    /** GLKv3 wire type labels; names match native `glkv3::wire_type_name`. */
    enum class WireType(val manifestName: String) {
        UInt("uint"),
        Int("int"),
        Bool("bool"),
        Str("str"),
        Bin("bin"),
        Array("array"),
    }

    /**
     * The terminal token used when a document carries no combination token.
     * Taken from the loaded catalogue ([CombinationCatalog.defaultSpec]) instead
     * of a literal, so the fallback tracks the native-exported whitelist.
     */
    val DEFAULT_TERMINAL: String get() = CombinationCatalog.defaultSpec.terminal.token

    /** The native-exported GLKv3 manifest, on the runtime classpath. */
    const val MANIFEST_RESOURCE: String = "profile-manifest-v3.tsv"

    /** Manifest columns: owner, path, wire, required, default, source, doc. */
    /** owner, path, wire, required, default, source, doc, width (native export R2+). */
    private const val MANIFEST_COLUMNS = 8
    private val WIDTHS = setOf(1, 2, 4, 8)

    /**
     * A manifest wire declaration: exactly one kind, or a UNION of kinds for the
     * dynamic plugin paths (plugin.<id>.params.* / .extract.*, contract-design
     * §3.14.7.7). Every member must come from the wire-kind vocabulary; an
     * unknown member fails closed while the manifest is parsed.
     */
    private data class Declaration(
        val owner: String,
        val wires: List<WireType>,
        /**
         * The v2 owner declaration's own bit width (1/2/4/8), or null for a
         * width-less kind (str/array export \"-\"; bool always exports 1).
         * The manifest is the single authority: this is carried so the value
         * can be range-checked against the declared width instead of silently
         * wrapping (e.g. 2^40 in a u32 field).
         */
        val width: Int?,
    ) {
        /** The single kind; the union paths resolve theirs from the descriptor. */
        val wire: WireType
            get() = wires.singleOrNull()
                ?: error(
                    "GLKv3 union declaration needs a plugin descriptor for its concrete type",
                )

        /** Manifest spelling: one name, or the "|"-joined union. */
        val manifestName: String get() = wires.joinToString("|") { it.manifestName }
    }

    /**
     * Owner-qualified native path -> wire declaration, generated by parsing the
     * manifest resource. The manifest (not this file) is the single Kotlin
     * authority: a field added or retyped natively only needs a regenerated
     * manifest.
     */
    /**
     * Fail-closed width column (native export R2+).
     *
     * The manifest is the single authority for a field's bit width, and the
     * width is a HARD VALIDATION INPUT: the adapter rejects a raw numeric value
     * that does not fit it instead of letting a typed cast wrap it. A width-less
     * kind (str/array) exports \"-\"; bool exports 1. Anything else -- a missing
     * column, a non-number, or a value outside 1/2/4/8 -- is a manifest defect
     * and fails closed here rather than being defaulted silently.
     */
    internal fun parseWidthColumn(column: String, line: String): Int? {
        if (column == "-") return null
        val width = column.toIntOrNull()
        require(width != null && width in WIDTHS) {
            "manifest width must be one of $WIDTHS or \"-\", got \"$column\": $line"
        }
        return width
    }

    private val DECLARATIONS: Map<String, Declaration> by lazy {
        val stream = NativeProfileGlkv3Adapter::class.java.classLoader
            ?.getResourceAsStream(MANIFEST_RESOURCE)
            ?: error("missing GLKv3 manifest resource: $MANIFEST_RESOURCE")
        stream.bufferedReader().useLines { lines ->
            val out = linkedMapOf<String, Declaration>()
            for (raw in lines) {
                val line = raw.trimEnd('\r')
                if (line.isBlank() || line.startsWith("#")) continue
                val parts = line.split('\t')
                require(parts.size == MANIFEST_COLUMNS) {
                    "manifest line needs $MANIFEST_COLUMNS tab-separated columns: $line"
                }
                val width = parseWidthColumn(parts[7], line)
                val owner = parts[0]
                val path = parts[1]
                val wires = parts[2].split('|').map { name ->
                    WireType.entries.firstOrNull { it.manifestName == name }
                        ?: error("unknown GLKv3 wire type in manifest: $line")
                }
                require(wires.isNotEmpty() && wires.distinct().size == wires.size) {
                    "malformed GLKv3 wire declaration in manifest: $line"
                }
                require(out.put(path, Declaration(owner, wires, width)) == null) {
                    "duplicate GLKv3 manifest path: $path"
                }
            }
            out
        }
    }

    /**
     * Every (path, manifest wire spelling) pair this adapter can emit, for the
     * manifest agreement test. A dynamic path keeps its union spelling.
     */
    /**
     * Declared bit width per path (null for width-less kinds), for the manifest
     * agreement/guard tests. The manifest stays the single authority.
     */
    internal fun declaredWidths(): Map<String, Int?> =
        DECLARATIONS.mapValues { it.value.width }

    fun declaredTypeNames(): Map<String, String> =
        DECLARATIONS.mapValues { it.value.manifestName }

    /**
     * The single wire kind declared for [path], or null when the path is not
     * declared or is a union (dynamic plugin path). Callers that must know a
     * concrete kind use this; the union case is resolved from the descriptor.
     */
    fun declaredWire(path: String): WireType? = DECLARATIONS[path]?.wires?.singleOrNull()

    /**
     * The declared bit width for [path], or null when the path is undeclared or
     * its kind is width-less (str/array). Mirrors [declaredWire]: the manifest is
     * the single authority, and a malformed width already failed closed while the
     * manifest was parsed, so this never returns a guessed default.
     */
    fun declaredWidth(path: String): Int? = DECLARATIONS[path]?.width

    /**
     * Declaration for a concrete path, including the dynamic plugin paths. The
     * manifest declares those with the literal placeholder `<id>`
     * (`plugin.<id>.enabled`, `plugin.<id>.params.*`, …); a concrete
     * `plugin.<some.id>.enabled` resolves ONLY when that declared row exists —
     * there is no implicit prefix rule.
     */
    private fun declarationFor(path: String): Declaration? {
        DECLARATIONS[path]?.let { return it }
        if (!path.startsWith("plugin.")) return null
        /* A plugin id may itself contain dots (demo.plugin, vivo.vr_guard), so
         * the concrete path is matched against each declared placeholder tail:
         * the manifest row must exist, and the segment before the tail is the
         * id. No implicit prefix rule. */
        val rest = path.removePrefix("plugin.")
        for ((tail, declaration) in DECLARATIONS.entries
            .filter { it.key.startsWith("plugin.<id>.") }
            .map { it.key.removePrefix("plugin.<id>.") to it.value }) {
            if (tail.endsWith(".*")) {
                val marker = "." + tail.dropLast(1)
                val at = rest.indexOf(marker)
                if (at > 0) return declaration
            } else if (rest.length > tail.length + 1 && rest.endsWith("." + tail)) {
                return declaration
            }
        }
        return null
    }

    /** Maps a dynamically typed plugin value onto its wire kind. */
    private fun wireOf(value: PluginValue): WireType = when (value) {
        is PluginValue.UInt -> WireType.UInt
        is PluginValue.Int -> WireType.Int
        is PluginValue.Bool -> WireType.Bool
        is PluginValue.Str -> WireType.Str
    }

    /** M2: one declared queue element -> its wire map (encoder sorts the keys). */
    private fun glkv3QueueElement(element: QueueElement): Glkv3Value {
        require((element.step == null) != (element.seam == null)) {
            "queue element needs exactly one of step/seam"
        }
        return Glkv3Value.Map(
            buildList {
                element.step?.let { add("step" to Glkv3Value.Str(it)) }
                element.seam?.let { add("seam" to Glkv3Value.Str(it)) }
                element.stage?.let { add("stage" to Glkv3Value.Str(it)) }
            },
        )
    }

    private fun glkv3Of(value: PluginValue): Glkv3Value = when (value) {
        is PluginValue.UInt -> Glkv3Value.UInt(value.value)
        is PluginValue.Int -> Glkv3Value.Int(value.value)
        is PluginValue.Bool -> Glkv3Value.Bool(value.value)
        is PluginValue.Str -> Glkv3Value.Str(value.value)
    }

    /** Owner column of every declared path (owner-qualified manifest). */
    fun declaredOwners(): Map<String, String> = DECLARATIONS.mapValues { it.value.owner }

    /**
     * Translates the logical document into the canonical GLKv3 logical
     * document. S4 R6b: the root terminal token is DERIVED from the document's
     * combination token (single source of truth); when no token is present the
     * safe root_child default is used. 43284 documents are route-less: the root
     * `route` key is always omitted there, whatever the logical routeKind.
     */
    fun adapt(document: NativeProfileDocument): Glkv3Document {
        val sections = document.v3Sections().map { section ->
            val entries = buildList {
                for ((key, raw) in section.entries) {
                    val path = "${section.name}.$key"
                    val declaration = declarationFor(path)
                        ?: error("NativeProfileDocument emitted an unmapped GLKv3 path: $path")
                    add(Glkv3Entry(key, toValue(declaration.wire, raw)))
                }
                /* S4 R4: String fields (the 43284 policy paths) ride the same
                 * manifest declaration and must be declared str. */
                for ((key, text) in section.textEntries) {
                    val path = "${section.name}.$key"
                    val declaration = declarationFor(path)
                        ?: error("NativeProfileDocument emitted an unmapped GLKv3 path: $path")
                    add(Glkv3Entry(key, toText(declaration.wire, text)))
                }
                /* P1: plugin parameters are dynamically typed; the manifest
                 * declares a union and the descriptor picked the concrete kind,
                 * so membership is what gets checked here. */
                for ((key, value) in section.pluginEntries) {
                    val path = "${section.name}.$key"
                    val declaration = declarationFor(path)
                        ?: error("NativeProfileDocument emitted an unmapped GLKv3 path: $path")
                    require(wireOf(value) in declaration.wires) {
                        "plugin parameter $path is not declared as ${wireOf(value).manifestName}"
                    }
                    add(Glkv3Entry(key, glkv3Of(value)))
                }
                /* M2: the step queue is an array of maps. The element shape
                 * (exactly one of step/seam, stage only with seam) was already
                 * validated at the declaration boundary (ProfileLayout); here
                 * only the declared wire kind is enforced. */
                for ((key, elements) in section.queueEntries) {
                    val path = "${section.name}.$key"
                    val declaration = declarationFor(path)
                        ?: error("NativeProfileDocument emitted an unmapped GLKv3 path: $path")
                    require(declaration.wires.singleOrNull() == WireType.Array) {
                        "GLKv3 path $path is declared ${declaration.manifestName}, not array"
                    }
                    require(elements.isNotEmpty()) { "GLKv3 path $path: queue must not be empty" }
                    add(Glkv3Entry(key, Glkv3Value.Array(elements.map(::glkv3QueueElement))))
                }
            }
            Glkv3Section(name = section.name, entries = entries)
        }
        val is43284 = document.backendKind == BackendKind.Cve2026_43284.wire.toUInt()

        val adapted = Glkv3Document(
            /* HOCON refactor: the kernel scalars are ROOT values. */
            kernelMajor = document.kernelMajor.toULong(),
            kernelMinor = document.kernelMinor?.toULong(),
            safeMode = document.safeMode != 0u,
            release = document.release,
            terminal = document.combination?.terminal?.token ?: DEFAULT_TERMINAL,
            /* 43284 documents are route-less (native RouteKind::None since S4 F3;
             * the legacy kRouteAuto sentinel is decode-only): the token has no
             * route axis, so the root "route" key is always omitted. */
            backend = BackendKind.fromWire(document.backendKind.toInt())?.token,
            route = if (is43284) null else RouteKind.fromWire(document.routeKind)?.token,
            sections = sections,
        )
        /* PERMANENT SELF-DIAGNOSTIC (READ-BACK, deliberately NOT tautological): compare
         * the terminal the adapter actually WROTE into the produced structure with the
         * one the document carries. Comparing the source expression with itself would be
         * vacuous; reading the produced value is what localises a lost terminal to THIS
         * line (firing) or to the encoder below (passing while the bytes stay short). */
        /* Only when the document DECLARES a combination: the "none" class legitimately
         * has none and correctly falls back to DEFAULT_TERMINAL. */
        val documentTerminal = document.combination?.terminal?.token
        if (documentTerminal != null) {
            require(adapted.terminal == documentTerminal) {
                "adapter wrote=" + adapted.terminal + " doc=" + documentTerminal +
                    " release=" + document.release
            }
        }
        return adapted
    }

    private fun toValue(type: WireType, raw: ULong): Glkv3Value = when (type) {
        WireType.UInt -> Glkv3Value.UInt(raw)
        WireType.Int -> Glkv3Value.Int(raw.toLong())
        WireType.Bool -> Glkv3Value.Bool(raw != 0uL)
        /* A numeric logical field emitted for a declared str path is a bug. */
        WireType.Str, WireType.Bin, WireType.Array ->
            error("GLKv3 path is not a numeric or boolean section field")
    }

    /**
     * S4 R4 String mapping. [Glkv3Encoder] bounds the UTF-8 byte length at the
     * native 256-byte maximum, so an over-long path fails closed at encode time.
     */
    private fun toText(type: WireType, text: String): Glkv3Value = when (type) {
        WireType.Str -> Glkv3Value.Str(text)
        else -> error("GLKv3 path is not a string section field")
    }
}
