package com.ghostlock.app.data.profile

import com.ghostlock.app.data.NativeProfileDocument
import com.ghostlock.app.data.component.BackendKind
import com.ghostlock.app.data.route.RouteKind

/**
 * NativeProfileDocument (logical model) -> Glkv3Document path/type adapter
 * (GLKv3-3, S4 R2).
 *
 * This adapter is the production logical-document translation
 * used by `exportKernelProfiles` and the app native-document path (GLKv3-4).
 * It consumes [NativeProfileDocument.v3Sections], the owner-qualified and
 * selection-aware emission (only the selection's owners plus `common`).
 *
 * S4 R2 removes the hand-written path -> type table: the map is generated from
 * the native-exported GLKv3 manifest `profile-manifest-v3.tsv` (owner, path, wire,
 * required, default, source, doc) shipped as a profile-core runtime resource.
 * A key or wire type that drifts on either side fails
 * ProfileManifestV3AgreementTest instead of silently reaching production.
 *
 * The root selection keys are tokens (release / terminal / backend / route), as
 * the GLKv3 root map declares.
 */
object NativeProfileGlkv3Adapter {
    /** GLKv3 wire type labels; names match native `glkv3::wire_type_name`. */
    enum class WireType(val manifestName: String) {
        UInt("uint"),
        Int("int"),
        Bool("bool"),
        Str("str"),
        Bin("bin"),
        Array("array"),
    }

    /** The root_child terminal token (the default frontend selection). */
    const val TERMINAL_ROOT_CHILD: String = "root_child"

    /** The umh_forward terminal token (43284's catalogued handoff). */
    const val TERMINAL_UMH_FORWARD: String = "umh_forward"

    /** The native-exported GLKv3 manifest, on the runtime classpath. */
    const val MANIFEST_RESOURCE: String = "profile-manifest-v3.tsv"

    /** Manifest columns: owner, path, wire, required, default, source, doc. */
    private const val MANIFEST_COLUMNS = 7

    private data class Declaration(val owner: String, val wire: WireType)

    /**
     * Owner-qualified native path -> wire declaration, generated by parsing the
     * manifest resource. The manifest (not this file) is the single Kotlin
     * authority: a field added or retyped natively only needs a regenerated
     * manifest.
     */
    private val DECLARATIONS: Map<String, Declaration> by lazy {
        val stream = NativeProfileGlkv3Adapter::class.java.classLoader
            ?.getResourceAsStream(MANIFEST_RESOURCE)
            ?: error("missing GLKv3 manifest resource: $MANIFEST_RESOURCE")
        stream.bufferedReader().useLines { lines ->
            val out = linkedMapOf<String, Declaration>()
            for (raw in lines) {
                val line = raw.trimEnd('\r')
                if (line.isBlank() || line.startsWith("#")) continue
                val parts = line.split('\t')
                require(parts.size == MANIFEST_COLUMNS) {
                    "manifest line needs $MANIFEST_COLUMNS tab-separated columns: $line"
                }
                val owner = parts[0]
                val path = parts[1]
                val wire = WireType.entries.firstOrNull { it.manifestName == parts[2] }
                    ?: error("unknown GLKv3 wire type in manifest: $line")
                require(out.put(path, Declaration(owner, wire)) == null) {
                    "duplicate GLKv3 manifest path: $path"
                }
            }
            out
        }
    }

    /** Every (path, wire) pair this adapter can emit, for manifest agreement. */
    fun declaredTypes(): Map<String, WireType> = DECLARATIONS.mapValues { it.value.wire }

    /** Owner column of every declared path (owner-qualified manifest). */
    fun declaredOwners(): Map<String, String> = DECLARATIONS.mapValues { it.value.owner }

    /**
     * Translates the logical document into the canonical GLKv3 logical
     * document. [terminal] is the resolved terminal token; it defaults to the
     * root_child terminal so every existing caller keeps byte-identical output.
     * The sparse catalogue resolves 43284 to [TERMINAL_UMH_FORWARD].
     */
    fun adapt(
        document: NativeProfileDocument,
        terminal: String = TERMINAL_ROOT_CHILD,
    ): Glkv3Document {
        val sections = document.v3Sections().map { section ->
            val entries = buildList {
                for ((key, raw) in section.entries) {
                    val path = "${section.name}.$key"
                    val declaration = DECLARATIONS[path]
                        ?: error("NativeProfileDocument emitted an unmapped GLKv3 path: $path")
                    add(Glkv3Entry(key, toValue(declaration.wire, raw)))
                }
                /* S4 R4: String fields (the 43284 policy paths) ride the same
                 * manifest declaration and must be declared str. */
                for ((key, text) in section.textEntries) {
                    val path = "${section.name}.$key"
                    val declaration = DECLARATIONS[path]
                        ?: error("NativeProfileDocument emitted an unmapped GLKv3 path: $path")
                    add(Glkv3Entry(key, toText(declaration.wire, text)))
                }
            }
            Glkv3Section(name = section.name, entries = entries)
        }
        return Glkv3Document(
            release = document.release,
            terminal = terminal,
            /* 43284 documents are route-less (native kRouteAuto); fromWire(0) is
             * null, so the root "route" key is omitted. */
            backend = BackendKind.fromWire(document.backendKind.toInt())?.token,
            route = RouteKind.fromWire(document.routeKind)?.token,
            sections = sections,
        )
    }

    private fun toValue(type: WireType, raw: ULong): Glkv3Value = when (type) {
        WireType.UInt -> Glkv3Value.UInt(raw)
        WireType.Int -> Glkv3Value.Int(raw.toLong())
        WireType.Bool -> Glkv3Value.Bool(raw != 0uL)
        /* A numeric logical field emitted for a declared str path is a bug. */
        WireType.Str, WireType.Bin, WireType.Array ->
            error("GLKv3 path is not a numeric or boolean section field")
    }

    /**
     * S4 R4 String mapping. [Glkv3Encoder] bounds the UTF-8 byte length at the
     * native 256-byte maximum, so an over-long path fails closed at encode time.
     */
    private fun toText(type: WireType, text: String): Glkv3Value = when (type) {
        WireType.Str -> Glkv3Value.Str(text)
        else -> error("GLKv3 path is not a string section field")
    }
}
