/* ADR-0006 T1-T4 pin: the root handoff script TEXT is part of the attack path.
 *
 * The generator is parameterized by safe_mode (terminal/root_script.hpp) and this
 * test freezes the EXACT bytes it emits for both settings, so a later edit that
 * changes the script text - however innocent it looks - fails here instead of
 * shipping silently. The frozen digests come from the implementation landed in
 * 7169801 (the ADR-0006 T1-T4 commit, which parameterized the generator) and the
 * generated bytes have been identical since.
 *
 * The checked-in reference files under tests/data/root_script_pin carry the full
 * expected text so a mismatch reports the FIRST DIFFERING OFFSET with context
 * rather than only a digest; the digests are the fast check. The host test owns
 * the runtime snapshot (no CoreSession), so the generator sees a fixed home and
 * writes into a scratch directory under /tmp. */

#include "terminal/root_script.hpp"

#include "session/runtime_config.h"
#include "support/sha256.hpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>

#include <sys/stat.h>

namespace ghostlock::config {
    /* Test-local snapshot: the generator reads home_dir (baked into the text) and
     * root_script_path (where the text is written). Both are fixed here so the
     * emitted bytes are deterministic on any host. */
    RuntimeConfig &runtime_config_snapshot() noexcept {
        static RuntimeConfig config;
        return config;
    }
} // namespace ghostlock::config

namespace {
    constexpr const char *kScratchDir = "/tmp/ghostlock-root-script-pin";
    constexpr const char *kScratchScript = "/tmp/ghostlock-root-script-pin/.ghostlock_root.sh";

    /* Frozen digests: sha256 of the generated text for both safe_mode settings. */
    constexpr const char *kPinSafeModeOff =
        "90e9bb9e3a628126c882ad49dc5c9311f98d62f93a22fbebb5c497794ad2bbd9";
    constexpr const char *kPinSafeModeOn =
        "272609363478210a19fa465c8d7a8337f9ba0e1a49ae30535d48474b2268e4e6";

    std::string read_all(const char *path) {
        std::string out;
        std::FILE *file = std::fopen(path, "rb");
        if (file == nullptr) return out;
        char buffer[4096];
        std::size_t read = 0;
        while ((read = std::fread(buffer, 1, sizeof(buffer), file)) > 0) {
            out.append(buffer, read);
        }
        std::fclose(file);
        return out;
    }

    std::string digest_of(const std::string &text) {
        std::uint8_t digest[ghostlock::support::kSha256DigestBytes] = {0};
        ghostlock::support::sha256(
            reinterpret_cast<const std::uint8_t *>(text.data()), text.size(), digest);
        std::string hex(2 * ghostlock::support::kSha256DigestBytes, static_cast<char>(0));
        for (std::size_t i = 0; i < ghostlock::support::kSha256DigestBytes; ++i) {
            std::snprintf(&hex[2 * i], 3, "%02x", digest[i]);
        }
        return hex;
    }

    /* Byte comparison against the checked-in reference: reports the first
     * differing offset plus a short context window from both sides. */
    bool same_bytes(
        const std::string &actual, const std::string &expected, const char *label,
        const char *reference) {
        if (actual == expected) return true;
        std::size_t offset = 0;
        while (offset < actual.size() && offset < expected.size() &&
               actual[offset] == expected[offset]) {
            ++offset;
        }
        std::printf("root_script_pin_test: %s MISMATCH at offset %zu "
                    "(actual %zu bytes, reference %zu bytes)\n",
                    label, offset, actual.size(), expected.size());
        std::printf("  reference %s\n", reference);
        for (int32_t side = 0; side < 2; ++side) {
            const std::string &text = side == 0 ? actual : expected;
            std::printf("  %s: ", side == 0 ? "actual   " : "reference");
            for (std::size_t i = 0; i < 48 && offset + i < text.size(); ++i) {
                const unsigned char byte = static_cast<unsigned char>(text[offset + i]);
                if (byte >= 32 && byte < 127) {
                    std::printf("%c", static_cast<char>(byte));
                } else {
                    std::printf("\\x%02x", static_cast<unsigned int>(byte));
                }
            }
            std::printf("\n");
        }
        return false;
    }
} // namespace

int32_t main(void) {
    (void)mkdir(kScratchDir, 0700);
    auto &config = ghostlock::config::runtime_config_snapshot();
    config.home_dir = kScratchDir;
    config.root_script_path = kScratchScript;

    struct Mode {
        bool safe_mode;
        const char *pin;
        const char *reference;
        const char *label;
    };
    const Mode modes[2] = {
        {false, kPinSafeModeOff, GHOSTLOCK_ROOT_SCRIPT_PIN_DIR "/safe_mode_off.sh", "safe_mode=false"},
        {true, kPinSafeModeOn, GHOSTLOCK_ROOT_SCRIPT_PIN_DIR "/safe_mode_on.sh", "safe_mode=true"},
    };

    bool ok = true;
    for (const Mode &mode : modes) {
        ghostlock::terminal::write_root_script(mode.safe_mode);
        const std::string text = read_all(kScratchScript);
        if (text.empty()) {
            std::printf("root_script_pin_test: %s produced no script at %s\n",
                        mode.label, kScratchScript);
            return 1;
        }
        const std::string digest = digest_of(text);
        if (digest != mode.pin) {
            std::printf("root_script_pin_test: %s DIGEST MISMATCH got %s want %s\n",
                        mode.label, digest.c_str(), mode.pin);
            ok = false;
        }
        const std::string reference = read_all(mode.reference);
        if (reference.empty()) {
            std::printf("root_script_pin_test: missing reference %s\n", mode.reference);
            return 1;
        }
        if (!same_bytes(text, reference, mode.label, mode.reference)) ok = false;
    }
    if (!ok) return 1;
    std::puts("root_script_pin_test: OK");
    return 0;
}
