package com.ghostlock.app.data.profile

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import org.msgpack.core.MessagePack
import org.msgpack.value.Value

/**
 * GLKv3 Kotlin encoder tests (GLKv3-2).
 *
 * The byte-equality cases compare [Glkv3Encoder] output against golden vectors
 * produced by the **unmodified native** `glkv3::encode` (MPack) writer, so a
 * divergence in key order or integer width fails here. The minimal vector is
 * also asserted by native `core/tests/glkv3_codec_test.cpp`.
 */
class Glkv3EncoderTest {

    /* ---- Golden hex generated by native glkv3::encode (read-only harness) ---- */

    /** schema=3, release="r": root {release, schema, sections}. */
    private val minimalGolden = "83a772656c65617365a172a6736368656d6103a873656374696f6e7380"

    /** schema=3, release="r", meta.kernel_major=300, offset.{init_task=128, slide=-33}. */
    private val shortestGolden = "83a772656c65617365a172a6736368656d6103a873656374696f6e7382a46d65746181ac6b65726e656c5f6d616a6f72cd012ca66f666673657482a9696e69745f7461736bcc80a5736c696465d0df"

    /** The native codec test's `sample_document()`: every wire type, 4 sections. */
    private val sampleGolden = "86a76261636b656e64ae6376655f323032365f3433343939a772656c65617365d928352e31352e3138392d616e64726f696431332d382d30303031362d67353162626134333039616163a5726f757465b06d756c7469636173745f776169746572a6736368656d6103a873656374696f6e7384a4626c6f6281a77061796c6f6164c403010203a46c69737481a676616c75657393cd012cc3a178a46d65746182ac6b65726e656c5f6d616a6f7205a9736166655f6d6f6465c2a66f666673657482a9696e69745f7461736bce02112400a5736c696465fea87465726d696e616caa726f6f745f6368696c64"

    /** Sections U+E000 then U+10000: UTF-8 byte order differs from UTF-16 order. */
    private val utf8SortGolden = "82a6736368656d6103a873656374696f6e7382a3ee808081a16b01a4f090808081a16b02"

    /* ---- Native cross-check goldens ---- */

    @Test
    fun minimalDocumentMatchesNativeGolden() {
        val encoded = Glkv3Encoder.encode(Glkv3Document(release = "r"))
        assertEquals(minimalGolden, hex(encoded))
    }

    @Test
    fun shortestIntegerDocumentMatchesNativeGolden() {
        val document = Glkv3Document(
            release = "r",
            sections = listOf(
                Glkv3Section("meta", listOf(Glkv3Entry("kernel_major", Glkv3Value.UInt(300u)))),
                Glkv3Section(
                    "offset",
                    listOf(
                        Glkv3Entry("init_task", Glkv3Value.UInt(128u)),
                        Glkv3Entry("slide", Glkv3Value.Int(-33)),
                    ),
                ),
            ),
        )
        val encoded = Glkv3Encoder.encode(document)
        assertEquals(shortestGolden, hex(encoded))
        assertTrue(hex(encoded).contains("cd012c")) // uint16 300
        assertTrue(hex(encoded).contains("cc80"))   // uint8 128
        assertTrue(hex(encoded).contains("d0df"))   // int8 -33
        assertFalse(hex(encoded).contains("ce0000012c"))
    }

    @Test
    fun typedSampleDocumentMatchesNativeGolden() {
        assertEquals(sampleGolden, hex(Glkv3Encoder.encode(sampleDocument())))
    }

    @Test
    fun sectionKeysSortByUtf8ByteOrderLikeNative() {
        // U+10000 is the surrogate pair \uD800\uDC00; Kotlin has no \u{...} escape.
        val astral = "\uD800\uDC00"
        val document = Glkv3Document(
            sections = listOf(
                Glkv3Section(astral, listOf(Glkv3Entry("k", Glkv3Value.UInt(2u)))),
                Glkv3Section("\uE000", listOf(Glkv3Entry("k", Glkv3Value.UInt(1u)))),
            ),
        )
        assertEquals(utf8SortGolden, hex(Glkv3Encoder.encode(document)))
        assertTrue(Glkv3Encoder.compareUtf8Bytes("\uE000", astral) < 0)
        assertTrue("\uE000".compareTo(astral) > 0) // UTF-16 disagrees
    }

    /* ---- Canonical determinism ---- */

    @Test
    fun canonicalBytesAreStable() {
        assertArrayEquals(
            Glkv3Encoder.encode(sampleDocument()),
            Glkv3Encoder.encode(sampleDocument()),
        )
    }

    @Test
    fun insertionOrderDoesNotAffectCanonicalBytes() {
        val reference = Glkv3Encoder.encode(sampleDocument())
        val reordered = Glkv3Document(
            release = "5.15.189-android13-8-00016-g51bba4309aac",
            terminal = "root_child",
            backend = "cve_2026_43499",
            route = "multicast_waiter",
            sections = sampleDocument().sections.reversed().map { section ->
                section.copy(entries = section.entries.reversed())
            },
        )
        assertArrayEquals(reference, Glkv3Encoder.encode(reordered))
    }

    /* ---- Shortest integer forms (native mpack_write_u64 / mpack_write_i64) ---- */

    @Test
    fun uintUsesShortestFormAtEveryBoundary() {
        assertValuePrefix(Glkv3Value.UInt(0u), "00")
        assertValuePrefix(Glkv3Value.UInt(127u), "7f")
        assertValuePrefix(Glkv3Value.UInt(128u), "cc80")
        assertValuePrefix(Glkv3Value.UInt(255u), "ccff")
        assertValuePrefix(Glkv3Value.UInt(256u), "cd0100")
        assertValuePrefix(Glkv3Value.UInt(65535u), "cdffff")
        assertValuePrefix(Glkv3Value.UInt(65536u), "ce00010000")
        assertValuePrefix(Glkv3Value.UInt(4294967295u), "ceffffffff")
        assertValuePrefix(Glkv3Value.UInt(4294967296u), "cf0000000100000000")
        assertValuePrefix(Glkv3Value.UInt(Long.MAX_VALUE.toULong()), "cf7fffffffffffffff")
        assertValuePrefix(Glkv3Value.UInt(1uL shl 63), "cf8000000000000000")
        assertValuePrefix(Glkv3Value.UInt(ULong.MAX_VALUE), "cfffffffffffffffff")
    }

    @Test
    fun signedIntUsesShortestFormAtEveryBoundary() {
        assertValuePrefix(Glkv3Value.Int(0), "00")
        assertValuePrefix(Glkv3Value.Int(127), "7f")
        assertValuePrefix(Glkv3Value.Int(128), "cc80") // matches mpack_write_i64
        assertValuePrefix(Glkv3Value.Int(-1), "ff")
        assertValuePrefix(Glkv3Value.Int(-32), "e0")
        assertValuePrefix(Glkv3Value.Int(-33), "d0df")
        assertValuePrefix(Glkv3Value.Int(-128), "d080")
        assertValuePrefix(Glkv3Value.Int(-129), "d1ff7f")
        assertValuePrefix(Glkv3Value.Int(-32768), "d18000")
        assertValuePrefix(Glkv3Value.Int(-32769), "d2ffff7fff")
        assertValuePrefix(Glkv3Value.Int(Int.MIN_VALUE.toLong()), "d280000000")
        assertValuePrefix(Glkv3Value.Int(Int.MIN_VALUE.toLong() - 1L), "d3ffffffff7fffffff")
        assertValuePrefix(Glkv3Value.Int(Long.MIN_VALUE), "d38000000000000000")
    }

    /* ---- Types, presence, structure ---- */

    @Test
    fun wireTypesSurviveTheMessagePackUnpacker() {
        val root = unpackRoot(sampleDocument())
        val sections = root.mapGet("sections")
        val meta = sections.mapGet("meta")
        assertEquals(5L, meta.mapGet("kernel_major").asIntegerValue().toLong())
        assertEquals(false, meta.mapGet("safe_mode").asBooleanValue().boolean)
        val offset = sections.mapGet("offset")
        assertEquals(34677760L, offset.mapGet("init_task").asIntegerValue().toLong())
        assertEquals(-2L, offset.mapGet("slide").asIntegerValue().toLong())
        assertArrayEquals(byteArrayOf(1, 2, 3), sections.mapGet("blob").mapGet("payload").asBinaryValue().asByteArray())
        val values = sections.mapGet("list").mapGet("values").asArrayValue().list()
        assertEquals(3, values.size)
        assertEquals(300L, values[0].asIntegerValue().toLong())
        assertEquals(true, values[1].asBooleanValue().boolean)
        assertEquals("x", values[2].asStringValue().asString())
    }

    @Test
    fun explicitFalseIsRetainedAndAbsentOptionalFieldsAreOmitted() {
        val sample = hex(Glkv3Encoder.encode(sampleDocument()))
        assertTrue(sample.contains("a9736166655f6d6f6465c2")) // "safe_mode" -> false
        assertTrue(sample.contains("7465726d696e616c"))       // sample carries terminal

        val minimal = hex(Glkv3Encoder.encode(Glkv3Document(release = "r")))
        assertFalse(minimal.contains("7465726d696e616c"))     // omitted, not null/empty
    }

    @Test
    fun rootPresenceFollowsKeyOccurrence() {
        val root = unpackRoot(sampleDocument())
        // backend, release, route, schema, sections, terminal.
        assertEquals(6, root.asMapValue().size())
    }

    /* ---- R2 bounded UTF-8 strings ---- */

    @Test
    fun stringValueRoundTripsAtTheByteBound() {
        val text = "日本語-" + "a".repeat(256 - "日本語-".toByteArray(Charsets.UTF_8).size)
        assertEquals(Glkv3Encoder.MAX_STRING_BYTES, text.toByteArray(Charsets.UTF_8).size)
        val document = Glkv3Document(
            release = "r",
            terminal = "root_child",
            backend = "cve_2026_43499",
            sections = listOf(Glkv3Section("s", listOf(Glkv3Entry("k", Glkv3Value.Str(text))))),
        )
        val decoded = Glkv3Decoder.decode(Glkv3Encoder.encode(document))
        assertEquals(
            Glkv3Value.Str(text),
            decoded!!.sections.first { it.name == "s" }.entries.first { it.key == "k" }.value,
        )
    }

    @Test
    fun stringLongerThanTheBoundIsRejected() {
        val tooLong = "a".repeat(Glkv3Encoder.MAX_STRING_BYTES + 1)
        val document = Glkv3Document(
            sections = listOf(Glkv3Section("s", listOf(Glkv3Entry("k", Glkv3Value.Str(tooLong))))),
        )
        try {
            Glkv3Encoder.encode(document)
            fail("encoder accepted a string over MAX_STRING_BYTES")
        } catch (_: IllegalArgumentException) {
            // expected: fail closed before the wire
        }
    }

    /* ---- Helpers ---- */

    /** Native canonical documents carry schema then sections; the value follows a fixed prefix. */
    private fun assertValuePrefix(value: Glkv3Value, expectedValueHex: String) {
        val document = Glkv3Document(
            sections = listOf(Glkv3Section("s", listOf(Glkv3Entry("k", value)))),
        )
        val encoded = hex(Glkv3Encoder.encode(document))
        val prefix = "82a6736368656d6103a873656374696f6e7381a17381a16b"
        assertEquals(prefix + expectedValueHex, encoded)
    }

    private fun sampleDocument(): Glkv3Document = Glkv3Document(
        release = "5.15.189-android13-8-00016-g51bba4309aac",
        terminal = "root_child",
        backend = "cve_2026_43499",
        route = "multicast_waiter",
        sections = listOf(
            Glkv3Section(
                "meta",
                listOf(
                    Glkv3Entry("kernel_major", Glkv3Value.UInt(5u)),
                    Glkv3Entry("safe_mode", Glkv3Value.Bool(false)),
                ),
            ),
            Glkv3Section(
                "offset",
                listOf(
                    Glkv3Entry("init_task", Glkv3Value.UInt(34677760u)),
                    Glkv3Entry("slide", Glkv3Value.Int(-2)),
                ),
            ),
            Glkv3Section(
                "blob",
                listOf(Glkv3Entry("payload", Glkv3Value.Bin(byteArrayOf(1, 2, 3)))),
            ),
            Glkv3Section(
                "list",
                listOf(
                    Glkv3Entry(
                        "values",
                        Glkv3Value.Array(
                            listOf(Glkv3Value.UInt(300u), Glkv3Value.Bool(true), Glkv3Value.Str("x")),
                        ),
                    ),
                ),
            ),
        ),
    )

    private fun unpackRoot(document: Glkv3Document): Value =
        MessagePack.newDefaultUnpacker(Glkv3Encoder.encode(document)).use { it.unpackValue() }

    private fun Value.mapGet(key: String): Value =
        asMapValue().map().entries.first { it.key.asStringValue().asString() == key }.value

    private fun hex(bytes: ByteArray): String =
        bytes.joinToString("") { "%02x".format(it.toInt() and 0xFF) }

    @Test
    fun mapEntriesAreEncodedInCanonicalKeyOrder() {
        fun document(entries: List<Pair<String, Glkv3Value>>) = Glkv3Document(
            release = "r",
            sections = listOf(
                Glkv3Section("meta", listOf(Glkv3Entry("queue", Glkv3Value.Map(entries)))),
            ),
        )
        val forward = document(
            listOf("z" to Glkv3Value.UInt(1u), "a" to Glkv3Value.UInt(2u)),
        )
        val reversed = document(
            listOf("a" to Glkv3Value.UInt(2u), "z" to Glkv3Value.UInt(1u)),
        )
        /* The entry order carried by the Kotlin value is a construction-time
         * determinism device only: the WIRE order is canonical (UTF-8 byte
         * order of the keys), so both encodings must be identical. */
        assertEquals(hex(Glkv3Encoder.encode(forward)), hex(Glkv3Encoder.encode(reversed)))
        val payload = hex(Glkv3Encoder.encode(forward))
        assertTrue(
            "canonical order must put a before z: " + payload,
            payload.indexOf("a161") < payload.indexOf("a17a"),
        )
    }

    @Test
    fun mapRoundTripsThroughTheDecoder() {
        val value = Glkv3Value.Map(
            listOf("a" to Glkv3Value.UInt(7u), "b" to Glkv3Value.Bool(true)),
        )
        /* The decoder validates the root: release/terminal/backend are required,
         * only `sections` is optional. */
        val document = Glkv3Document(
            release = "r",
            terminal = "root_child",
            backend = "cve_2026_43499",
            sections = listOf(
                Glkv3Section("meta", listOf(Glkv3Entry("queue", value))),
            ),
        )
        val decoded = requireNotNull(Glkv3Decoder.decode(Glkv3Encoder.encode(document)))
        assertEquals(value, decoded.sections.single().entries.single().value)
    }

    @Test
    fun duplicateMapKeysAreRejectedAtConstruction() {
        val thrown = assertThrows(IllegalArgumentException::class.java) {
            Glkv3Value.Map(listOf("a" to Glkv3Value.UInt(1u), "a" to Glkv3Value.UInt(2u)))
        }
        assertTrue(
            "a duplicate key must be rejected: " + thrown.message,
            thrown.message.orEmpty().contains("duplicate keys"),
        )
    }

}