package com.ghostlock.app.data.plugin

/**
 * One imported plugin: the App-side registry row (interface freeze 2026-10-05).
 *
 * The row records what was imported and where it lives; the plugin's own
 * parameter table never lives here (it comes from the native probe and the
 * overrides from the document), so a probe upgrade cannot leave stale schema
 * behind in the registry.
 */
data class PluginManifestEntry(
    val id: String,
    val version: String,
    val abiVersion: Int,
    /** Lower-case hex SHA-256 of the imported .so; the loader re-checks it. */
    val sha256: String,
    /** Root-relative path under GHOSTLOCK_HOME (PluginPaths layout). */
    val modulePath: String,
    val enabled: Boolean,
    /** Registered stage; null = the plugin's own default stage policy. */
    val stage: String?,
    val importedAtMs: Long,
)

/**
 * TSV codec for the imported-plugin registry. The file lives in the App's
 * no-backup root (a .so must never ride Android auto-backup), is generated by
 * [render] and consumed by [parse]; both are pure so the format is unit-tested
 * without touching the filesystem.
 */
object PluginManifest {
    const val HEADER: String =
        "# GhostLock imported plugins (P1). Managed by the App; do not edit by hand.\n" +
            "# Columns: id<TAB>version<TAB>abi_version<TAB>sha256<TAB>module_path<TAB>" +
            "enabled<TAB>stage<TAB>imported_at_ms\n"

    private const val COLUMNS = 8
    private const val NONE = "-"

    fun parse(text: String): List<PluginManifestEntry> {
        val out = mutableListOf<PluginManifestEntry>()
        val seen = mutableSetOf<String>()
        for (raw in text.lineSequence()) {
            val line = raw.trimEnd('\r')
            if (line.isBlank() || line.startsWith("#")) continue
            val parts = line.split('\t')
            require(parts.size == COLUMNS) {
                "plugin manifest line needs " + COLUMNS + " tab-separated columns: " + line
            }
            val id = parts[0]
            require(PluginPaths.isValidId(id)) { "plugin manifest has an invalid id: " + line }
            require(seen.add(id)) { "duplicate plugin id in manifest: " + id }
            val modulePath = parts[4]
            require(PluginPaths.isSafeModulePath(modulePath)) {
                "plugin manifest has an unsafe module path: " + line
            }
            val enabled = when (parts[5]) {
                "1" -> true
                "0" -> false
                else -> error("plugin manifest enabled must be 1/0: " + line)
            }
            val sha256 = parts[3]
            require(Regex("[0-9a-f]{64}").matches(sha256)) {
                "plugin manifest sha256 must be 64 lower-case hex chars: " + line
            }
            out += PluginManifestEntry(
                id = id,
                version = parts[1],
                abiVersion = parts[2].toIntOrNull()
                    ?: error("plugin manifest abi_version is not a number: " + line),
                sha256 = sha256,
                modulePath = modulePath,
                enabled = enabled,
                stage = parts[6].takeIf { it != NONE && it.isNotEmpty() },
                importedAtMs = parts[7].toLongOrNull()
                    ?: error("plugin manifest imported_at_ms is not a number: " + line),
            )
        }
        return out
    }

    fun render(entries: List<PluginManifestEntry>): String = buildString {
        append(HEADER)
        for (entry in entries.sortedBy { it.id }) {
            append(entry.id).append('\t')
            append(entry.version).append('\t')
            append(entry.abiVersion).append('\t')
            append(entry.sha256).append('\t')
            append(entry.modulePath).append('\t')
            append(if (entry.enabled) "1" else "0").append('\t')
            append(entry.stage ?: NONE).append('\t')
            append(entry.importedAtMs).append('\n')
        }
    }
}
